version: '3.8'

services:
  # Servi√ßo do PHP / Apache
  web:
    build: .
    container_name: essence_lingerie_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: always
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

  # Banco de Dados
  db:
    image: mysql:8.0
    container_name: essence_lingerie_db_container
    restart: always
    environment:
      MYSQL_DATABASE: essence_lingerie_db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: essence_pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db

volumes:
  db_data: